'use strict';
const form=document.querySelector('#form'), $=s=>document.querySelector(s), F=window.AirspaceForm;
let context=null,zones=[],busy=false,session=null,serial=0,connected=false,scopeOptionsKey='',readError=false,connectionScope=null,connectionSession=null,zonePending=null;
const id=()=> 'airspace-'+Date.now()+'-'+Math.random().toString(36).slice(2,8);
const note=(text)=>{$('#message').textContent=text;};
function save(){const values={};for(const e of form.elements)if(e.name)values[e.name]=e.value;sessionStorage.setItem('sim-airspace-draft',JSON.stringify(values));}
function fill(data){for(const [key,value] of Object.entries(data)){if(!form.elements[key])continue;form.elements[key].value=key==='boundary'?JSON.stringify(value,null,2):['valid_from','valid_to','effective_at'].includes(key)?F.local(value):value??'';}toggle();save();}
function availability(){const upsert=form.elements.action.value!=='WITHDRAW';form.elements.scope.disabled=!upsert||!context?.scopes?.length;$('#zones').disabled=!upsert||!zones.length;$('#submit').disabled=busy||!connected||!context||(upsert&&!context.scopes.length);}
function toggle(){const withdrawing=form.elements.action.value==='WITHDRAW';$('#upsert').hidden=withdrawing;$('#withdraw').hidden=!withdrawing;for(const e of $('#upsert').querySelectorAll('input,select,textarea'))e.disabled=withdrawing;form.elements.effective_at.required=withdrawing;availability();}
function renderScopes(scopes,message){
 const key=JSON.stringify([scopes,message]);
 if(key!==scopeOptionsKey){
  const previous=context?.scopes?.find((s,i)=>String(i)===form.elements.scope.value);
  form.elements.scope.replaceChildren(new Option(message,''),...scopes.map((s,i)=>new Option(s.owner_org_name+' · '+s.district_name,String(i))));
  const index=previous?scopes.findIndex(s=>s.owner_org_id===previous.owner_org_id&&s.district_id===previous.district_id):-1;
  form.elements.scope.value=index>=0?String(index):'';
  scopeOptionsKey=key;
 }
 $('#scope-hint').textContent=scopes.length?'仅显示当前账号已授权的单位与区县。':message;
}
function clearRead(message='请先登录系统，再读取归属资料'){renderScopes([],message);context=null;$('#records').textContent=message;$('#receipt').textContent='资料读取不可用；草稿保留';availability();}
// Updates keep the airspace's own owner; otherwise an empty choice follows the simulator connection's unit and district.
function defaultScope(owned){if(!context||form.elements.action.value==='WITHDRAW')return;const latest=F.latestFor(context.items,form.elements.airspace_no.value.trim()),own=F.scopeIndex(context.scopes,latest?.payload),value=owned&&own?own:form.elements.scope.value||F.defaultScope(context.scopes,latest,connectionScope);if(value!==form.elements.scope.value){form.elements.scope.value=value;save();}}
// What depends on accepted receipts: the zone's airspace number, its next revision, an unused message ID and the owner.
async function zoneContext(zone){const no=F.zoneAirspaceNo(zone,context.items,await F.stableAirspaceNo(zone.id)),latest=F.latestFor(context.items,no);form.elements.airspace_no.value=no;form.elements.revision.value=latest?Number(latest.revision)+1:1;if(context.items.some(item=>item.message_id===form.elements.message_id.value.trim()))form.elements.message_id.value=id();defaultScope(true);save();}
const adjusted=(changes,body)=>changes.length?'已按系统已接收记录自动'+changes.map(c=>c==='message_id'?'换用新的消息编号':c==='revision'?'将修订次序调为 '+body.revision:'将'+(c==='valid_from'?'生效':'撤销生效')+'时间顺延至 '+F.local(body[c]).replace('T',' ')).join('、')+'。':'';
async function call(path,body){const requestedSession=session;let response;try{response=await fetch('/api/external/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});}catch{throw Error(body?.method==='POST'?'提交结果未知，请恢复服务后刷新记录，再使用原消息重试。':'模拟器服务不可用');}const data=await response.json();if(response.status===401&&requestedSession===session){serial++;clearRead();throw Error('系统登录失效，请重新登录；草稿已保留。');}if(requestedSession!==session)throw Error('账号已切换，旧请求结果已忽略；草稿保留。');if(!response.ok)throw Error(data.error||'请求失败');return data;}
async function refresh(){if(busy)return;const run=++serial;try{const status=await call('status');if(run!==serial)return;if(readError){note('');readError=false;}$('#status').textContent=status.connected?'已登录 '+(status.user?.name||status.user?.account||'系统'):'尚未登录系统';if(session!==status.session_version){session=status.session_version;clearRead();}connected=!!status.connected;$('#login').textContent=connected?'系统连接':'登录系统';if(!connected){clearRead();return;}if(!context)clearRead('正在读取归属资料');if(connectionSession!==session){connectionSession=session;connectionScope=await call('connection-scope').catch(()=>null);if(run!==serial)return;}const next=await call('request',{method:'GET',path:'/local-interface-simulator/airspaces/context'});if(run!==serial)return;renderScopes(next.scopes,next.scopes.length?'请选择归属单位与区县':'当前账号没有可用的归属范围，请联系管理员配置');context=next;availability();if(zonePending){const zone=zones.find(z=>z.id===zonePending);zonePending=null;if(zone&&$('#zones').value===zone.id)await zoneContext(zone);}defaultScope(false);$('#records').replaceChildren();for(const item of next.items){const row=document.createElement('article');row.className='external-record';const text=document.createElement('p');text.textContent=`${item.payload?.name||item.airspace_no} · ${item.airspace_no} · 第 ${item.revision} 次 · ${item.action==='WITHDRAW'?'已受理撤销':'已受理下发'} · 模拟`;row.append(text);for(const action of ['UPSERT','WITHDRAW']){const button=document.createElement('button');button.type='button';button.textContent=action==='UPSERT'?(item.action==='WITHDRAW'?'重新下发草稿':'更新草稿'):'撤销草稿';button.onclick=()=>{form.reset();form.elements.scope.value='';form.elements.name.value='';form.elements.boundary.value='';form.elements.min_altitude_m.value='';form.elements.max_altitude_m.value='';form.elements.altitude_datum.value='';const payload=item.payload||{};const index=context.scopes.findIndex(s=>s.owner_org_id===payload.owner_org_id&&s.district_id===payload.district_id);fill({...payload,scope:index>=0?index:'',airspace_no:item.airspace_no,message_id:id(),revision:item.revision+1,action,valid_from:F.nextEffective(item),effective_at:F.nextEffective(item),valid_to:null,change_reason:''});note(item.action==='WITHDRAW'&&action==='UPSERT'?'该空域已撤销，请重新填写原空域名称、归属、种类、边界与高度资料后下发。':'已生成同一空域的新操作草稿');};row.append(button);}const details=document.createElement('details'),summary=document.createElement('summary'),pre=document.createElement('pre');summary.textContent='接收回执与原始提交';pre.textContent=JSON.stringify(item,null,2);details.append(summary,pre);row.append(details);$('#records').append(row);}if(!next.items.length)$('#records').textContent='尚无已下发模拟空域';}catch(e){if(run!==serial)return;readError=true;clearRead('归属资料读取失败：'+e.message);note(e.message);}}
form.addEventListener('input',save);form.elements.action.addEventListener('change',toggle);
$('#new').onclick=()=>{form.reset();fill({message_id:id(),airspace_no:'',revision:1,valid_from:Date.now(),boundary:{type:'Polygon',coordinates:[]}});note('新草稿已创建');};
form.onsubmit=async e=>{e.preventDefault();if(busy)return;try{if(!connected||!context)throw Error('请先登录并成功读取系统资料');await refresh();if(!connected||!context)throw Error('请先登录并成功读取系统资料');
 // Reconcile with fresh receipts so issuing the same airspace again is a new delivery rather than a reused message.
 const prepared=F.prepareIssue(F.payload(Object.fromEntries(new FormData(form)),context.scopes),context.items,{id}),body=prepared.body,key=body.action==='WITHDRAW'?'effective_at':'valid_from';
 if(prepared.changes.length)fill({message_id:body.message_id,revision:body.revision,[key]:body[key]});
 busy=true;$('#submit').disabled=true;const result=await call('request',{method:'POST',path:'/local-interface-simulator/airspaces',key:body.message_id,body});$('#receipt').textContent=JSON.stringify(result,null,2);
 // The accepted message is used up; an unknown result (thrown above) keeps it so the retry stays idempotent.
 fill({message_id:id(),revision:Number(result.revision||body.revision)+1,[key]:F.nextEffective({payload:body})});
 note((prepared.replay?'该消息此前已被系统受理，本次返回原回执，未重复生成新版本。':'系统已受理第 '+result.revision+' 次'+(body.action==='WITHDRAW'?'撤销':'下发')+'，请在业务空域页刷新查看。')+adjusted(prepared.changes,body)+'表单已换用新的消息编号，再次提交即为下一次下发。');
}catch(error){note(error.message);}finally{busy=false;availability();await refresh();}};
$('#refresh').onclick=refresh;
$('#login').onclick=()=>parent===window?location.assign('/'):parent.postMessage({type:'simulator-airspace-login'},location.origin);
$('#zones-draw').onclick=()=>{const kind=form.elements.kind_code.value;if(!kind){note('请先选择空域类型，再绘制边界');form.elements.kind_code.focus();return;}save();if(parent===window){location.assign('/?input=airspaces');return;}parent.postMessage({type:'simulator-airspace-draw',kind_code:kind},location.origin);};
form.elements.kind_code.addEventListener('change',()=>{if($('#zones').value)parent.postMessage({type:'simulator-airspace-kind',id:$('#zones').value,kind_code:form.elements.kind_code.value},location.origin);});
$('#zones-refresh').onclick=()=>parent.postMessage({type:'simulator-airspace-zones'},location.origin);
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent)return;if(e.data?.type==='simulator-airspace-zones'){zones=e.data.zones||[];const previous=$('#zones').value;$('#zones').replaceChildren(new Option(zones.length?'请选择已绘制空域':'暂无边界，请点击绘制空域边界',''),...zones.map((z,i)=>new Option(z.name,z.id||String(i))));$('#zones').value=[...$('#zones').options].some(o=>o.value===previous)?previous:'';$('#zones').disabled=!zones.length;$('#zones-hint').textContent=zones.length?'选择后沿用地图边界；绘制只保存草稿，提交下发后平台才接收。':'请先选择空域类型，再点击“绘制空域边界”，完成后自动回填。';if(e.data.selected_id){$('#zones').value=e.data.selected_id;$('#zones').onchange();}}if(e.data?.type==='simulator-input-view'&&e.data.visible){refresh();$('#zones-refresh').click();}});
// Choosing a map zone prepares its delivery: geometry, kind, altitude and name come from the zone so it can be issued directly.
$('#zones').onchange=async()=>{const zone=zones.find((z,i)=>(z.id||String(i))===$('#zones').value);if(!zone)return;form.elements.action.value='UPSERT';toggle();form.elements.boundary.value=JSON.stringify(zone.boundary,null,2);if(zone.kind_code)form.elements.kind_code.value=zone.kind_code;if(zone.max_altitude_m!=null){form.elements.min_altitude_m.value=zone.min_altitude_m??0;form.elements.max_altitude_m.value=zone.max_altitude_m;form.elements.altitude_datum.value=zone.altitude_datum||'AMSL';}form.elements.name.value=zone.name;if(!form.elements.change_reason.value.trim())form.elements.change_reason.value='地图空域“'+zone.name+'”模拟下发';$('#boundary-summary').textContent='已使用地图空域：'+zone.name;save();if(context)await zoneContext(zone);else zonePending=zone.id;};
$('#file').onchange=async()=>{try{const file=$('#file').files[0];if(!file)return;if(file.size>120000)throw Error('边界文件过大，请使用较小文件');form.elements.boundary.value=JSON.stringify(F.geometry(await file.text()),null,2);save();note('边界已导入草稿，尚未提交');}catch(e){note(e.message);}};
try{const draft=JSON.parse(sessionStorage.getItem('sim-airspace-draft'));if(draft){for(const [key,value]of Object.entries(draft))if(form.elements[key])form.elements[key].value=value;toggle();}else $('#new').click();}catch{$('#new').click();}
parent.postMessage({type:'simulator-input-ready'},location.origin);$('#zones-refresh').click();refresh();let timer=setInterval(()=>{if(!document.hidden)refresh();},10000);window.addEventListener('pagehide',()=>{clearInterval(timer);serial++;});
